CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nickname VARCHAR(255) NOT NULL,
    avatar VARCHAR(255),
    weichat_id VARCHAR(255) NOT NULL,
    level TEXT NOT NULL,
    token_info TEXT,
    extras TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    openid VARCHAR(512),
    unionid VARCHAR(512),
    nickname VARCHAR(512),
    headimgurl VARCHAR(512),
    token_infos VARCHAR(512),
    user_level VARCHAR(64),
    extras VARCHAR(1024),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
